language: ruby

services:
  - docker

script:
  - echo "Ritik@123" | docker login -u "161b178" --password-stdin
  - docker build --target backendBuilder -t 161b178/ebook-backend .
  - docker build --target rpBuilder -t 161b178/ebook-proxy .
  - docker push 161b178/ebook-backend
  - docker push 161b178/ebook-proxy