version: "3.2"
services:
  client:
    image: node:10.12.0-alpine
    working_dir: /apps/ah
    command: npm start -- --host 0.0.0.0 --disable-host-check
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: ./client
        target: /apps/ah

  reverse-proxy:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.ah.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./wait-for
        target: /wait/wait-for
    depends_on:
      - web
      - client

  web:
    image: node:8.16.0
    working_dir: /apps/ah
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
    env_file: .env
    command: npm run dev
    volumes:
      - type: bind
        source: .
        target: /apps/ah
    depends_on:
      - db

  db:
    image: mongo:4.1
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./docker/volumes/mongo
        target: /data/db



